version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "${WWW_PORT}:80"
    volumes:
      - ./web:/var/www/html/web
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./web:/var/www/html/web
    environment:
      - E_WP_ENV=development
      - E_DB_HOST=mysql
      - E_DB_USER=${DB_USER}
      - E_DB_PASSWORD=${DB_PASS}
      - E_DB_NAME=${DB_NAME}
      - E_HOSTNAME=${HOSTNAME}:${WWW_PORT}
    links:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    volumes:
      - ./data/db/dumps/dbseed.sql.gz:/docker-entrypoint-initdb.d/dbseed.sql.gz
      - ./data/db/mysql:/var/lib/mysql
volumes:
  web:
  config:
  scripts:
  mysqldata:
